### PR TITLE
Update code for Python3 compatibility

### PR DESCRIPTION
**Pull request by ahwillia**
I added some quick fixes to get this code working with Python3. I also locally tested on Python2 and everything still works fine. Would you like to include these changes?

### CODE REVIEW

**Comment by kimjingu** [comment]
Thank you! Sure I would like to incorporate. I would like to use this opportunity to improve these implementation a little bit and add some proper test cases. Would it be ok to apply this patch after the clean up?

**Comment by ahwillia** [comment]
Yep that sounds good. Thanks for providing the code!

**Comment by kimjingu** [comment]
Sorry for the late follow up. When I tried executing example.py with python3, still some errors related to print statement remains. Would you be up for making a few more modifications to make this work (e.g., try making example.py runs)?

**Comment by ahwillia** [comment]
done, though this may have been superceded by #3

**Comment by kimjingu** [comment]
Thanks! I found minor issues from the both and instead of asking for fixes in both, I followed up [#3](https://github.com/kimjingu/nonnegfac-python/pull/3).

**Comment by ahwillia** [comment]
Ok I'll close this in favor of #3

**Comment by kimjingu** [comment]
Thanks for the help, Alex, and also for the nice Julia package. :)

**Pull request closed without merging**
